baseURL: "https://datastorytelling.netlify.app/"
languageCode: en
DefaultContentLanguage: en
title: R para comunicadores
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
params:
  author: Ricardo Mayer
  customCss: []
  customJs: []
  description: Materiales data storytelling
  doNotLoadAnimations: no
  favicon: favicons/
  images: images/site-feature-image.png
  keywords: ''
  mainSections: post
  math:
    enable: no
    use: katex
  profilePicture: images/profile.png
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://de.linkedin.com/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/ricardomayerb/rparacomunicadores/
    - icon: fab fa-instagram
      title: instagram
      url: https://www.instagram.com/
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:cien@mail.udp.cl
  title: R storytelling
menu:
  main:
#    - identifier: home
#      name: Home
#      url: /
#      weight: 100
    - identifier: posts
      name: Secciones
      url: /post/
      weight: 100
    - identifier: about
      name: About
      url: /about/
      weight: 200
